---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - serviceentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - serviceentries/finalizers
  verbs:
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - serviceentries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - istioadaptiverequestoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - istioadaptiverequestoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - istioadaptiverequestoptimizers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - serviceentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - serviceentries/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - serviceentries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - weightoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - weightoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - weightoptimizers/status
  verbs:
  - get
  - patch
  - update
